### ISSUE TITLE
Should we add an engines field to the package.json

### ISSUE THREAD

**Issue by jkvyff** [vanillaes/absurdum#110]
Perhaps as this repo requires very new feature, it could check node version as a catch for people trying out the repo but getting strange errors and returning a more helpful error.

I also wonder what the best way to find the min version required.

```
{ 
  "engines" : { "node" : ">=13.3.0" } 
}
```

**Comment by evanplaice** [comment]
I'm a bit conflicted about this. This library ships a CommonJS compatibility bundle so it can be used with pre-13.2 versions of Node.

We could add pkg.engines and update the notes about backward compatibility in README.md

What do you think?

**Comment by evanplaice** [comment]
If you want to add it to both `absurdum` and `computer-science`, I'm good with it.

**Comment by jkvyff** [comment]
So what would prompt someone to check pkg.engines in that case?
If just the readme, perhaps just having update notes there is simpler/more maintainable.

And functionality of the library could have a differing requirement from developing/testing it.

**Comment by evanplaice** [comment]
`pkg.engines` works by throwing a warning during install if the node version is too low

Adding a short note to README.md like I did [here](https://github.com/vanillaes/csv-es#commonjs) should be enough.

A year from now, these patterns won't be so bleeding edge. For now, if `pkg.engines` becomes an annoyance, we'll hear about it from the users in the issues. Otherwise, I wouldn't stress about it too much.

**Comment by evanplaice** [comment]
Trust me. If this package becomes popular (ie consistent >2K weekly downloads) we'll start to hear from users about every single little flaw.

Good OSS projects aren't good because of the devs who write them. They're good because users relentlessly nitpick even the sloppiest code bases into good shape. That's the beauty of OSS.
