### ISSUE TITLE
How should we handle Words breakdown?

### ISSUE THREAD

**Issue by jkvyff** [vanillaes/absurdum#201]
Words could behave many different ways to match words by default:
- Simple for those familiar with regex, matching /[\w]+/ and build out for specific cases later if desired.
- An opposite implementation of what we have for splitting before cases(snake, camel, kebab)
- Exactly behavior of Lodash for those familiar with its intricacies.

## References 

 - [_.words](https://lodash.com/docs/4.17.15#words)

**Comment by evanplaice** [comment]
TBH, I don't know. I like how Lodash makes the pattern configurable. That leaves the question, "What should the default behavior be?"

Does it make sense to split on spaces, match words but also remove punctuation chars? So.

> This is a sentence, "containing a quote?"

... would return

```javascript
[ 'This',  'is',  'a',  'sentence', 'containing', 'a', 'quote']
```

That leaves one nasty edge case, single-quotes. A word containing a single-quote could be the end of a title. Ex

> sometimes single-quotes are used for titles like 'The Book of Titles'

But it is also commonly used as a conjunction

> Don't remove the single-quote in don't

And other times to indicate possession

> Joe's take was good but Dennis' was better

The context-specific ambiguity of Natural Language is... challenging.

-----

Since users can define their own pattern, I'm cool with doing the same as Lodash and avoiding this complexity altogether.
