### ISSUE TITLE
Change operators with Object.entries to use Object.keys to improve cross browser compatibility

### ISSUE THREAD

**Issue by jkvyff** [vanillaes/absurdum#205]
As you pointed out, Object.entries is not supported by internet explorer.

All methods using Object.Entries should be able to be reworked to use Object.keys, do you see any downsides?

## References 

 - [Object.entries](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries)
 - [Object.keys](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys)

**Comment by evanplaice** [comment]
> All methods using Object.Entries should be able to be reworked to use Object.keys, do you see any downsides?

No. When this project started, IE support wasn't really considered. Now that I've spent many hours digging through documentation to plan the scope, I think adding 'ie polyfill' as a selling point will be good to attract users.

Since this change is non-breaking, lets table it until after the 1.0 release.
